# owner: systems
# file: roles/configure.dns/tasks/hostsfile.yml
# description: Tasks file to configure hostfile settings and entries
---
- name: Create/update /etc/hosts
  template:
    src: hostsfile.j2
    dest: /etc/hosts
    backup: yes
    owner: root
    group: root
    mode: 0644
  tags:
    - hostsfile
