# owner: systems
# file: roles/configure.dns/tasks/main.yml
# description: Main tasks file with include for DNS configuration and hostsfile entry.
---
- include: resolv.yml
  when: vmguest_network_type is defined and vmguest_network_type == "static"
  #- include: hostsfile.yml


- inclusde: firewall.yml
  when: firewallports is defined
