- name: create nfs-mount directory with parent directories
  file:
    path: /opt/nfs-mount/
    state: directory

- name: Install NFS mount utility
  become: true
  yum:
    name: nfs-utils
    state: present

- name: Mount NFS share
  become: true
  ansible.posix.mount:
    src: "10.10.200.31:/data"
    path: "/opt/nfs-mount"
    opts: 'rw,sync'
    state: mounted
    fstype: nfs
